name: CI Pipeline - TODO App (DevSecOps)

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-scan-run:
    runs-on: ubuntu-latest

    steps:
      # 1Ô∏è‚É£ Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2Ô∏è‚É£ Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      # 3Ô∏è‚É£ Build Docker images
      - name: Build Docker images
        run: docker compose build

      # 4Ô∏è‚É£ Install Trivy
      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget https://github.com/aquasecurity/trivy/releases/latest/download/trivy_0.50.1_Linux-64bit.deb
          sudo dpkg -i trivy_0.50.1_Linux-64bit.deb

            # 5Ô∏è‚É£ Trivy Scan - All App Images
      - name: Trivy Scan - TODO App Images
        run: |
          images=(
            todo-auth
            todo-users
            todo-todos
            todo-log-processor
            todo-app
          )

          for image in "${images[@]}"; do
            echo "üîç Scanning image: $image"
            trivy image --severity HIGH,CRITICAL --exit-code 1 "$image"
          done


      # 6Ô∏è‚É£ Start containers
      - name: Start containers
        run: docker compose up -d

      # 7Ô∏è‚É£ Verify containers
        run: docker ps

      # 8Ô∏è‚É£ Stop containers
      - name: Stop containers
        run: docker compose down
